In [1]:
#Math with Numpy
import numpy as np

## Latihan-2 (2D array)


In [125]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n")
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size)
print('dimensi array = ', A.ndim)
print('ukuran array = ', A.shape, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3) 



## Latihan-3 (Slicing)

In [124]:
#Lengkapi kodingan berikut
print('baris ke-3 = \n', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2][0:2])
print('entry ke-2 & 3 kolom ke-3 = \n', A[1:3,2:]) #Baris 1-2 kolom >= 2

baris ke-3 = 
 [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 = 
 [[6]
 [9]]


## Latihan-4 (Operasi matriks)

In [132]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])
# 2*A 
print("2xA : \n", 2*A)
# 2+A
print("2+A : \n", 2+A)
# A+B
print("A+B : \n", A+B)
# A-B
print("A-B : \n", A-B)
# det(A)
print("det(A) : ", np.linalg.det(A))

2xA : 
 [[ 2  4]
 [14 16]]
2+A : 
 [[ 3  4]
 [ 9 10]]
A+B : 
 [[ 4  7]
 [ 8 14]]
A-B : 
 [[-2 -3]
 [ 6  2]]
det(A) :  -6.0


In [142]:
#invers dari B, simpan jadi matriks D
D = np.linalg.inv(B)
print("D :\n",D, "\n")
#transpose D
print("D^T : \n", D.transpose(), "\n")
#nilai eigen dan vektor eigen dari A dan B
print("Eigen Value A :", np.linalg.eig(A)[0])
print("Eigen Vector A:\n", np.linalg.eig(A)[1],"\n")
print("Eigen Value B :", np.linalg.eig(B)[0])
print("Eigen Vector B:\n", np.linalg.eig(B)[1])

D :
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] 

D^T : 
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] 

Eigen Value A : [-0.62347538  9.62347538]
Eigen Vector A:
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] 

Eigen Value B : [1.8074176 7.1925824]
Eigen Vector B:
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


In [144]:
#Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?
print("BxD : \n",B*D)
print("BxD : \n",np.matmul(B,D))
#Metode perkalian nya beda , untuk yg pertama elemen x elemen, metode ke-2 baris x kolom

BxD : 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
BxD : 
 [[1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00]]


## Not Task, Only My Manuscript Journal

In [20]:
#Array Introduction 
#2D Array 
a = np.array([[1,2,3,4], [1,2,3,5], [4,5,6,7]])
print("Total : ", a.size, "Dimension : ", a.ndim, "Shape : ", a.shape)
print(a) #a.shape (row, column)

Total :  12 Dimension :  2 Shape :  (3, 4)
[[1 2 3 4]
 [1 2 3 5]
 [4 5 6 7]]


In [69]:
print(a[0][1:],"\n") #row 0 column >= 1
print(a[1:,:1],"\n") #same notation column and row

[2 3 4] 

[[1]
 [4]] 



In [42]:
#Normal Multiplication Elemen x Elemen
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)
print("B x B  : \n", b*b)
#Matrix Multiplication Row x Column 
print("B x B  : \n", np.matmul(b,b))
#Scalar Matrix Multiplication
print("const.B: \n", 2.2 * b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
B x B  : 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
B x B  : 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
const.B: 
 [[ 2.2  4.4  6.6]
 [ 8.8 11.  13.2]
 [15.4 17.6 19.8]]


In [45]:
#Matrix Determinan det(b)
print("det(b) : ", np.linalg.det(b))

det(b) :  6.66133814775094e-16


In [59]:
#Matrix Eigen Vector 
print("Eigen Value and Eigen Vector b : \n", np.linalg.eig(b), "\n")
print("Eigen Value b : ", np.linalg.eig(b)[0], "\n")
print("Eigen Vector b: ", np.linalg.eig(b)[1])

Eigen Value and Eigen Vector b : 
 (array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])) 

Eigen Value b :  [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16] 

Eigen Vector b:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [60]:
#Inverse Matrix 
print("b^-1 : ", np.linalg.inv(b))

b^-1 :  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
