## Numpy and Scipy for Basic Statistics

In [48]:
import numpy as np
from scipy import stats, mean, median
import math

In [44]:
#Measure of Central Tendency 
#Mean
A = np.array([math.sin(90), math.ceil(math.cos(45)), math.tan(75), math.sinh(math.tanh(10))]) 
print(A, "\n")
print("Mean : ", np.mean(A))
print("Mean : ", mean(A, axis = 0), "\n")
B = np.array([[1,3,4], [math.tanh(89),6,6.63], [math.pi, 3, 5], [3,5,7]])
print(B, "\n")
print("Mean Axis-0: ", mean(B, axis = 0), "\n") #Average per column
print("Mean Axis-1: ", mean(B, axis = 1))#Average per row
#mean(B, axis = 1)[0] = 2.6

[ 0.89399666  1.         -0.42070095  1.17520119] 

Mean :  0.6621242250655456
Mean :  0.6621242250655456 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 

Mean Axis-0:  [2.03539816 4.25       5.6575    ] 

Mean Axis-1:  [2.66666667 4.54333333 3.71386422 5.        ]


C:\Users\asus\AppData\Local\Temp/ipykernel_16708/2047619474.py:6: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  print("Mean : ", mean(A, axis = 0), "\n")
C:\Users\asus\AppData\Local\Temp/ipykernel_16708/2047619474.py:9: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  print("Mean Axis-0: ", mean(B, axis = 0), "\n") #Average per column
C:\Users\asus\AppData\Local\Temp/ipykernel_16708/2047619474.py:10: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  print("Mean Axis-1: ", mean(B, axis = 1))#Average per row


In [53]:
#Median 
print(A, "\n")
print("Median A : ", np.median(A))
print("Median A : ", median(A, axis = 0), "\n")
print(B, "\n")
print("Median B : ", np.median(B, axis = 0))
print("Median B : ", median(B, axis = 1))

[ 0.89399666  1.         -0.42070095  1.17520119] 

Median A :  0.9469983318002789
Median A :  0.9469983318002789 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 

Median B :  [2.    4.    5.815]
Median B :  [3.         6.         3.14159265 5.        ]


C:\Users\asus\AppData\Local\Temp/ipykernel_16708/169246630.py:4: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  print("Median A : ", median(A, axis = 0), "\n")
C:\Users\asus\AppData\Local\Temp/ipykernel_16708/169246630.py:7: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  print("Median B : ", median(B, axis = 1))


In [61]:
#Mode
print(A, "\n")
Arr, Frek = np.unique(A, return_counts = True)
Arr, Frek
idx = np.argmax(Frek)
print("Index : ", idx)
print("Mode A: ", Arr[idx])
print("Mode A: ", stats.mode(A), "\n")

print(B, "\n")
print("Mode B: ", stats.mode(B, axis = 0), "\n")
print("Mode B: ", stats.mode(B, axis = 1))

[ 0.89399666  1.         -0.42070095  1.17520119] 

Index :  0
Mode A:  -0.42070095062112434
Mode A:  ModeResult(mode=array([-0.42070095]), count=array([1])) 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 

Mode B:  ModeResult(mode=array([[1., 3., 4.]]), count=array([[2, 2, 1]])) 

Mode B:  ModeResult(mode=array([[1.],
       [1.],
       [3.],
       [3.]]), count=array([[1],
       [1],
       [1],
       [1]]))


In [70]:
#Measures of Spread
#Range = Max - Min
print(A, "\n")
print("Range A : ", A.max()-A.min(), "\n")
print(B, "\n")
print("Range B : ", B.max()-B.min(), "\n")

[ 0.89399666  1.         -0.42070095  1.17520119] 

Range A :  1.5959021379038731 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 

Range B :  6.0 



In [73]:
#Quartile
print(A, "\n")
# First quartile (Q1)
Q1 = np.quantile(A, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(A, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(A, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR, "\n")

print(B, "\n")
# First quartile (Q1)
Q1 = np.quantile(B, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(B, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(B, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

[ 0.89399666  1.         -0.42070095  1.17520119] 


Quartile 1: 0.23664785648971676
Quartile 2: 0.9469983318002789
Quartile 3: 1.0876005936413744

Interquartile Range 0.8509527371516576 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 


Quartile 1: 3.0
Quartile 2: 3.5707963267948966
Quartile 3: 5.5

Interquartile Range 2.5


C:\Users\asus\AppData\Local\Temp/ipykernel_16708/4194753207.py:4: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  Q1 = np.quantile(A, .25, interpolation = 'midpoint')
C:\Users\asus\AppData\Local\Temp/ipykernel_16708/4194753207.py:8: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  Q2 = np.quantile(A, .50, interpolation = 'midpoint')
C:\Users\asus\AppData\Local\Temp/ipykernel_16708/4194753207.py:12: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged t

In [76]:
#Percentile
print(A, "\n")
print("Percentile-35th : ",np.percentile(A, 35), "\n")
print(B, "\n")
print("Percentile-35th : ",np.percentile(B, 35), "\n")

[ 0.89399666  1.         -0.42070095  1.17520119] 

Percentile-35th :  0.89929683042053 

[[1.         3.         4.        ]
 [1.         6.         6.63      ]
 [3.14159265 3.         5.        ]
 [3.         5.         7.        ]] 

Percentile-35th :  3.0 

